config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :teachers, path_prefix: 'my'
  resources :teachers
  get 'teacher/course/:id' => 'teachers#course', as: 'teacher_course'
  get 'teacher/dashboard' => 'teachers#dashboard', as: 'teacher_dashboard'

  devise_for :students, path_prefix: 'my'
  resources :students
  get 'student/dashboard' => 'students#dashboard', as: 'student_dashboard'
  get 'student/course/:id' => 'students#course', as: 'student_course'
  get 'student/grade/:id' => 'students#grade', as: 'student_grade'
  get 'student/profile' => 'students#profile', as: 'student_profile'

  get 'student/change_grade/:id' => 'students#change_grade_student', as: 'change_grade_student'

  post 'student/enroll_student' => 'students#enroll_student', as: 'enroll_student'

  devise_for :users, path_prefix: 'my'
  resources :users

  resources :scores
  get 'score/edit_for_teacher/:id' => 'scores#edit_for_teacher', as: 'edit_score_for_teacher'

  resources :courses

  resources :grades

  resources :periods

  root 'welcome#index'

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :period
  has_and_belongs_to_many :students
  has_many :courses

  validates :name, presence: true

  scope :actual, ->{where current: true}
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:name, :period_id, :current)
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_for @grade, :html => { :class => "form-horizontal grade" } do |f| %>

  <% if @grade.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @grade.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :period_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :period_id,set_periods.collect{|p| [p.name, p.id]},{} , :class => 'form-control' %>
    </div>
    <%=f.error_span(:period_id) %>
  </div>
  <div class="form-group">
    <%= f.label :current, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :current,[['Cursando', true],['Finalizado', false]],{}, :class => 'form-control' %>
    </div>
    <%=f.error_span(:current) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                grades_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/grades/edit.html.erb
<%- model_class = Grade -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
<hr>
<div class="actuales">
  <h3><strong>Materias Actuales</strong></h3>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Maestro</th>
      <th>Periodo</th>
      <th>Estado</th>
      <th>Accion</th>
    </tr>
    </thead>
    <tbody>
    <% @grade.courses.each_with_index do |c, i| %>
    <tr>
      <th scope="row"><%= i+1 %></th>
      <td><%= c.name %></td>
      <td><%= full_name(c.teacher) %></td>
      <td><%= c.grade.period.name %></td>
      <td>
        <% if c.grade.current? %>
          <span class="label label-success">Cursando</span>
        <% else %>
          <span class="label label-danger">finalizado</span>
        <% end %>
      </td>
      <td>
        <%= link_to 'Ver detalles', '#', class: 'btn btn-xs btn-default' if student_signed_in? %>
        <%= link_to 'Editar', edit_course_path(c), class: 'btn btn-xs btn-default' if user_signed_in? %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div> <!-- Actuales -->

<h3><strong>Estudiantes</strong><small><strong> Cant. Inscritos: </strong><%= @grade.students.count %></small></h3>
<div class="row calificacion">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Email</th>
        <th>Telefono</th>
        <th>Accion</th>
      </tr>
      </thead>
      <tbody>
      <% @grade.students.each_with_index do|s, i|  %>
        <tr>
          <th scope="row"><%= i+1 %></th>
            <td><%= full_name(s) %></td>
            <td><%= s.email %></td>
            <td><%= s.phone %></td>
            <td><%= link_to 'Editar',edit_student_path(s),class: 'btn btn-xs btn-default' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/grades/index.html.erb
<%- model_class = Grade -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:period_id) %></th>
      <th><%= model_class.human_attribute_name(:current) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= link_to grade.id, grade_path(grade) %></td>
        <td><%= grade.name %></td>
        <td><%= grade.name %></td>
        <td>
          <% if grade.current? %>
            <span class="label label-success">Cursando</span>
          <% else%>
            <span class="label label-danger">Finalizado</span>
          <% end%>
        </td>
        <td><%=l grade.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_grade_path(grade), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      grade_path(grade),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_grade_path,
            :class => 'btn btn-primary' %>

app/views/grades/new.html.erb
<%- model_class = Grade -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/grades/show.html.erb
<%- model_class = Grade -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @grade.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:period_id) %>:</strong></dt>
  <dd><%= @grade.period_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current) %>:</strong></dt>
  <dd><%= @grade.current %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              grades_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_grade_path(@grade), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              grade_path(@grade),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>