config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :teachers, path_prefix: 'my'
  resources :teachers
  get 'teacher/course/:id' => 'teachers#course', as: 'teacher_course'
  get 'teacher/dashboard' => 'teachers#dashboard', as: 'teacher_dashboard'

  devise_for :students, path_prefix: 'my'
  resources :students
  get 'student/dashboard' => 'students#dashboard', as: 'student_dashboard'
  get 'student/course/:id' => 'students#course', as: 'student_course'
  get 'student/grade/:id' => 'students#grade', as: 'student_grade'
  get 'student/profile' => 'students#profile', as: 'student_profile'

  get 'student/change_grade/:id' => 'students#change_grade_student', as: 'change_grade_student'

  post 'student/enroll_student' => 'students#enroll_student', as: 'enroll_student'

  devise_for :users, path_prefix: 'my'
  resources :users

  resources :scores
  get 'score/edit_for_teacher/:id' => 'scores#edit_for_teacher', as: 'edit_score_for_teacher'

  resources :courses

  resources :grades

  resources :periods

  root 'welcome#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :grades
  has_many :scores
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :change_grade_student, :enroll_student]
  before_action :authenticate_user!, except: [:dashboard, :course, :profile, :grade]
  before_action :authenticate_student!, only: [:dashboard, :course, :profile, :grade]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_grade_student
  end

  def enroll_student
    grade = Grade.find(params[:grade_id])#busco el grado por el id mandado

    grade.courses.each do |c| #por cada cursos encontrado hacemos...
      c.scores.create(student_id: @student.id) #creamos las notas que pertenecen a este curso y pertenecen a este estudiante
    end
    if @student.grades << grade # sitodo lo anterior se ejecuta normalmente enrolamos el grado al estudiante
      redirect_to students_path, notice: 'El Estudiante ha sido inscrito a este grado' #y lo redireccionamos a la vista de estudiantes
    else
      logger.alert 'Cambio de Grado no se realizo exitosamente' #caso contrario agreagamos al registro un error y mostramos un mensaje
      render :change_grade_student #y redireccionamos a la vista de cambio de grado
    end
  end

  def dashboard
      #para mostrar las materias que esta cursando en el grado actual
      @courses = current_student.grades.actual.first.courses unless current_student.grades.actual.first.courses.blank?
      #para mostrar los grados que ya curso
      @grades_old = current_student.grades.where(current: false) unless current_student.grades.where(current: false).blank?
  end

  def course
    #mostrar el curso solicitado con sus respectivas notas
    @course = Course.find(params[:id])
    @scores = @course.scores.find_by student_id: current_student
  end

  def grade
    #obtener los datos del grado- un promedio de las notas-
    @grade = Grade.find(params[:id])
    #promedio
    @ss =0
    @grade.courses.each do |c|
      @ss = @ss + c.scores.where(student_id: current_student).first.score_final if c.scores.any?
    end
    @result = @ss / @grade.courses.count
  end

  def profile
    @student = current_student
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit([:name, :email, :password, :last_name, :genre, :birth, :mother, :father, :phone])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>

  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label 'Password', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>
  <div class="form-group">
    <%= f.label 'Nombres', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label 'Apellidos', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_name) %>
  </div>
  <div class="form-group">
    <%= f.label 'Genero', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.radio_button :genre, 'Mas' %> Masculino <br><br>
      <%= f.radio_button :genre, 'Fen' %> Femenino
    </div>
    <%=f.error_span(:genre) %>
  </div>
  <div class="form-group">
    <%= f.label 'Nacimiento', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :birth,{}, :class => 'form-control' %>
    </div>
    <%=f.error_span(:birth) %>
  </div>
  <div class="form-group">
    <%= f.label 'Madre', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mother, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mother) %>
  </div>
  <div class="form-group">
    <%= f.label 'Padre', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :father, :class => 'form-control' %>
    </div>
    <%=f.error_span(:father) %>
  </div>
  <div class="form-group">
    <%= f.label 'Tel/Cel', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Crear Estudiante', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("Cancelar")),
                students_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/students/change_grade_student.html.erb
<h1>Cambiar Grado</h1>
<hr>
<h3>Estudiante: <strong><%= full_name(@student)%> </strong></h3>
<p><stong>Grado Actual:</stong><%= @student.grades.where(current: true).first.name unless @student.grades.where(current: true).blank?%></p>
<p><stong>Periodo Actual:</stong><%= @student.grades.where(current: true).first.name unless @student.grades.where(current: true).blank?%></p>
<hr>
<%= form_tag(action:  :enroll_student) do %>
    <%= hidden_field_tag :id, @student.id %>
    <%= label_tag 'Nuevo Grado' %>
    <%= select_tag :grade_id, options_for_select(set_grades.collect { |g| [[g.name, g.period.name].join(" "), g.id]}),class: 'form-control' %>
    <br>
    <%= submit_tag 'Cambiar', class: 'btn btn-primary' %>
<% end %>

app/views/students/course.html.erb
<%= link_to '<< Atras', :back %>
<hr/>
<div class="course">
  <h2><small>Materia:</small><%= @course.name %></h2>
  <div class="well">
    <div class="row">
      <div class="col md 4">
        <strong>Profesor:</strong><%= link_to full_name(@course.teacher), "mailto:#{@course.teacher.email}" %>
      </div>
      <div class="col-md-4">
        <strong>Grado:</strong><%= @course.grade.name %>
      </div>
      <div class="col-md-4">
        <strong>Estatus:</strong>
        <% if @course.grade.current? %>
          <span class="label label-success">Cursando</span>
        <% else %>
          <span class="label label-danger">Finalizado</span>
        <% end %>
      </div>
    </div>
  </div>

  <h3>Calificaciones</h3>
  <div class="row calificacion">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong>Periodo:</strong><%= @course.grade.period.name %></h3>
        </div>

        <div class="panel-body">
          <% if @scores.blank? %>
            Tus Calificaciones aun han sido Publicadas.
          <% else %>
          <div class="row">
            <div class="col-md-2">
              <div class="well well-sm text-center"><h4><small>C1: </small><Strong><%= @scores.score_one %></Strong></h4></div>
            </div>
            <div class="col-md-2">
              <div class="well well-sm text-center"><h4><small>C2: </small><Strong><%= @scores.score_two %></Strong></h4></div>
            </div>
            <div class="col-md-2">
              <div class="well well-sm text-center"><h4><small>C3: </small><Strong><%= @scores.score_three %></Strong></h4></div>
            </div>
            <div class="col-md-2">
              <div class="well well-sm text-center"><h4><small>C4: </small><Strong><%= @scores.score_four %></Strong></h4></div>
            </div>
            <div class="col-md-4">
              <div class="well well-sm text-center"><h4><i class="fa fa-file-text-o"></i><small>Examen: </small>
                <strong><%= @scores.score_test %></strong></h4></div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="alert alert-success text-center" role="alert"><h4><small>Calificacion Final: </small>
            <strong><%= @course.grade.current? ? '-' : @scores.score_final %></strong></h4></div>
          </div>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/dashboard.html.erb
<div class="dashboard">
  <div class="jumbotron">
    <h2><strong>Hola <%= full_name(current_student) %>!</strong></h2>
    <p>Bienvenido a tu Colegio</p>
    <p><strong>Grado Actual: </strong><%= current_student.grades.actual.first.name unless current_student.grades.actual.first.name.blank? %></p>
    <p><strong>Periodo Actual: </strong><%= current_student.grades.actual.first.period.name unless current_student.grades.actual.first.period.name.blank? %></p>
    <%= link_to 'Ver mi Perfil', student_profile_path,class: 'btn btn-primary' %>
  </div>
</div>

<div class="actuales">
  <h3><strong>Materias Actuales</strong></h3>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Maestro</th>
      <th>Periodo</th>
      <th>Estado</th>
      <th>Accion</th>
    </tr>
    </thead>
    <tbody>
    <% @courses.each_with_index do |c, i| %>
        <tr>
          <th scope="row"><%= i+1 %></th>
          <td><%= c.name %></td>
          <td><%= full_name(c.teacher) %></td>
          <td><%= c.grade.period.name %></td>
          <td>
            <% if c.grade.current? %>
                <span class="label label-success">Cursando</span>
            <% else %>
                <span class="label label-danger">finalizado</span>
            <% end %>
          </td>
          <td>
            <%= link_to 'Ver detalles', student_course_path(c), class: 'btn btn-xs btn-default' if student_signed_in? %>
            <%= link_to 'Editar', edit_course_path(c), class: 'btn btn-xs btn-default' if user_signed_in? %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div> <!-- Actuales -->

<div class="antiguos">
  <% unless @grades_old.blank? %>
    <h3><strong>Grados finalizados</strong></h3>
      <% @grades_old.each do |g| %>
        <%= link_to "#{g.name} #{g.period.name}",student_grade_path(g),class: 'btn btn-info' %>
      <% end %>
  <% end %>
</div>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1>Editar Estudiante</h1>
</div>
<%= render :partial => 'form' %>

app/views/students/grade.html.erb
<%= link_to '<< Atras', student_dashboard_path %>
<hr/>
<div class="grade">
  <h2><small>Grado:</small><%= @grade.name %></h2>
    <div class="well">
      <div class="row">
        <div class="col md 4">
          <strong>Periodo:</strong><%= @grade.period.name %>
        </div>
        <div class="col-md-4">
          <strong>Estatus:</strong>
          <% if @grade.current? %>
              <span class="label label-success">Cursando</span>
          <% else %>
              <span class="label label-danger">Finalizado</span>
          <% end %>
        </div>
        <div class="col-md-4">
          <strong>Resultado:</strong>
          <% if @result >= 65 %>
            <p><a class="btn btn-md btn-success">PROMOVIDO</a> con un promedio de  <%= @result %></p>
          <% else %>
            <p><a class="btn btn-md btn-danger">REPROBADO</a> con un promedio de <%= @result %></p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="materias">
      <h3>Materias Cursadas</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Maestro</th>
            <th>Periodo</th>
            <th>Calificacion</th>
            <th>Accion</th>
          </tr>
        </thead>
        <tbody>
          <% @grade.courses.each_with_index do |c, i| %>
            <tr>
              <th scope="row"><%= i+1 %></th>
              <td><%=c.name  %></td>
              <td><%= full_name(c.teacher) %></td>
              <td><%= c.grade.period.name %></td>
              <td><strong><%= c.scores.where(student_id: current_student).first.score_final if c.scores.any? %></strong></td>
              <td><%= link_to 'Ver Detalles', student_course_path(c), class: 'btn btn-xs btn-default' %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>

</div>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name('Nombres') %></th>
      <th><%= model_class.human_attribute_name('Apellidos') %></th>
      <th><%= model_class.human_attribute_name('Genero') %></th>
      <th><%= model_class.human_attribute_name('Nacimiento') %></th>
      <th><%= model_class.human_attribute_name('Madre') %></th>
      <th><%= model_class.human_attribute_name('Padre') %></th>
      <th><%= model_class.human_attribute_name('Tel/Cel') %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.email %></td>
        <td><%= student.name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.genre %></td>
        <td><%= student.birth %></td>
        <td><%= student.mother %></td>
        <td><%= student.father %></td>
        <td><%= student.phone %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>

          <%= link_to 'Cambiar Grado',
                      change_grade_student_path(student), :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("Estudiante Nuevo")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1>Estudiante Nuevo </h1>
</div>
<%= render :partial => 'form' %>

app/views/students/profile.html.erb
<h1>Mi Perfil</h1>
</hr>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12 col-sm-8">
            <h2><%= full_name(@student) %></h2>
            <p><strong>Email: </strong><%= @student.email %></p>
            <p><strong>Geneo: </strong><%= @student.genre %></p>
            <p><strong>Fecha de Nacimiento: </strong><%= @student.birth %></p>
            <p><strong>Madre: </strong><%= @student.mother %></p>
            <p><strong>Padre: </strong><%= @student.father %></p>
            <p><strong>Telefonos: </strong><%= @student.phone %></p>
            <p><strong>Grados</strong>
              <% @student.grades.each do |g| %>
                <span class="label label-info"><%= "#{g.name} #{g.period.name}" %></span>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @student.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @student.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genre) %>:</strong></dt>
  <dd><%= @student.genre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birth) %>:</strong></dt>
  <dd><%= @student.birth %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mother) %>:</strong></dt>
  <dd><%= @student.mother %></dd>
  <dt><strong><%= model_class.human_attribute_name(:father) %>:</strong></dt>
  <dd><%= @student.father %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @student.phone %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>