config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :teachers, path_prefix: 'my'
  resources :teachers
  get 'teacher/course/:id' => 'teachers#course', as: 'teacher_course'
  get 'teacher/dashboard' => 'teachers#dashboard', as: 'teacher_dashboard'

  devise_for :students, path_prefix: 'my'
  resources :students
  get 'student/dashboard' => 'students#dashboard', as: 'student_dashboard'
  get 'student/course/:id' => 'students#course', as: 'student_course'
  get 'student/grade/:id' => 'students#grade', as: 'student_grade'
  get 'student/profile' => 'students#profile', as: 'student_profile'

  get 'student/change_grade/:id' => 'students#change_grade_student', as: 'change_grade_student'

  post 'student/enroll_student' => 'students#enroll_student', as: 'enroll_student'

  devise_for :users, path_prefix: 'my'
  resources :users

  resources :scores
  get 'score/edit_for_teacher/:id' => 'scores#edit_for_teacher', as: 'edit_score_for_teacher'

  resources :courses

  resources :grades

  resources :periods

  root 'welcome#index'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :courses
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:dashboard, :course]
  before_action :authenticate_teacher!, only: [:dashboard, :course]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    #listar las materias activas del maestro y las materias inactivas
    @course = current_teacher.courses.currents
    #listar las materias finaliozadas
    @old_courses = current_teacher.courses.old
  end

  def course
    @course = Course.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit([:name, :email, :last_name, :phone, :about, :password])
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for @teacher, :html => { :class => "form-horizontal teacher" } do |f| %>

  <% if @teacher.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @teacher.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
    <div class="form-group">
      <%= f.label 'Password', :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.password_field :encrypted_password, :class => 'form-control' %>
      </div>
      <%=f.error_span(:encrypted_password) %>
    </div>
  <div class="form-group">
    <%= f.label 'Nombres', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label 'Apellidos', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_name) %>
  </div>
  <div class="form-group">
    <%= f.label 'Tel/Cel', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
  <div class="form-group">
    <%= f.label 'Informacion', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :about, :class => 'form-control' %>
    </div>
    <%=f.error_span(:about) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("Cancelar")),
                teachers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/teachers/course.html.erb
<%= link_to '<< Atras', teacher_dashboard_path %>
<hr/>
<h2><small>Materia:</small><%= @course.name %></h2>
<div class="well">
  <div class="row">
    <div class="col-md-4">
      <strong>Profesor: </strong><%= link_to full_name(@course.teacher), "mailto:#{@course.teacher.email}" %>
      <br/>
      <strong>Estudiantes: </strong><%= @course.scores.count %>
    </div>
    <div class="col-md-4">
      <strong>Grado: </strong><%= @course.grade.name %> <br/>
      <strong>Periodo: </strong><%= @course.grade.period.name %>
    </div>
    <div class="col-md-4">
      <strong>Estatus:</strong>
      <% if @course.grade.current? %>
          <span class="label label-success">Cursando</span>
      <% else %>
          <span class="label label-danger">Finalizado</span>
      <% end %>
    </div>
  </div>
</div>

<h3>Estudiantes</h3>
<div class="row calificacion">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Q1</th>
        <th>Q2</th>
        <th>Q3</th>
        <th>Q4</th>
        <th>Examen</th>
        <th>Calificacion final</th>
      </tr>
      </thead>
      <tbody>
      <% @course.scores.each_with_index do |s, i| %>
          <tr>
            <th scope="row"><%= i+1 %></th>
            <td><%= full_name(s.student) %></td>
            <td><%= s.score_one %></td>
            <td><%= s.score_two %></td>
            <td><%= s.score_three %></td>
            <td><%= s.score_four %></td>
            <td><%= s.score_test %></td>
            <td><%= s.score_final %></td>
            <td><%= link_to 'Modificar Notas', edit_score_for_teacher_path(s), class: 'btn btn-xs btn-default' if @course.grade.current? %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/teachers/dashboard.html.erb
<div class="dashboard">
  <div class="jumbotron">
    <h2><strong>Hola Maestro <%= full_name(current_teacher) %>!</strong></h2>
    <p>Bienvenido a tu Colegio</p>
    <%= link_to 'Ver mi Perfil', edit_teacher_path(current_teacher),class: 'btn btn-primary' %>
  </div>
</div>

<div class="actuales">
  <h3><strong>Materias Actuales</strong></h3>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Grado</th>
      <th>Periodo</th>
      <th>Estado</th>
      <th>Accion</th>
    </tr>
    </thead>
    <tbody>
    <% @course.each_with_index do |c, i| %>
        <tr>
          <th scope="row"><%= i+1 %></th>
          <td><%= c.name %></td>
          <td><%= c.grade.name %></td>
          <td><%= c.grade.period.name %></td>
          <td>
            <% if c.grade.current? %>
                <span class="label label-success">Cursando</span>
            <% else %>
                <span class="label label-danger">finalizado</span>
            <% end %>
          </td>
          <td>
            <%= link_to 'Ver detalles', teacher_course_path(c), class: 'btn btn-xs btn-default' if student_signed_in? %>
            <%= link_to 'Editar', edit_course_path(c), class: 'btn btn-xs btn-default' if user_signed_in? %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div> <!-- Actuales -->

<div class="antiguos">
  <% unless @old_courses.blank? %>
      <h3><strong>Grados finalizados</strong></h3>
  <% end %>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Grado</th>
      <th>Periodo</th>
      <th>Estado</th>
      <th>Accion</th>
    </tr>
    </thead>
    <tbody>
    <% @old_courses.each_with_index do |c, i| %>
        <tr>
          <th scope="row"><%= i+1 %></th>
          <td><%= c.name %></td>
          <td><%= c.grade.name %></td>
          <td><%= c.grade.period.name %></td>
          <td>
            <% if c.grade.current? %>
                <span class="label label-success">Cursando</span>
            <% else %>
                <span class="label label-danger">finalizado</span>
            <% end %>
          </td>
          <td>
            <%= link_to 'Ver detalles', teacher_course_path(c), class: 'btn btn-xs btn-default' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/teachers/edit.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1>Editar Profesor</h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/index.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1>Profesores</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name('Nombres') %></th>
      <th><%= model_class.human_attribute_name('Apellidos') %></th>
      <th><%= model_class.human_attribute_name('Tel/Cel') %></th>
      <th><%= model_class.human_attribute_name('Informacion') %></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.email %></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.phone %></td>
        <td><%= teacher.about %></td>
        <td>
          <%= link_to t('.edit', :default => t("Editar")),
                      edit_teacher_path(teacher), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("Eliminar")),
                      teacher_path(teacher),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas Seguro?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("Nuevo Profesor")),
            new_teacher_path,
            :class => 'btn btn-primary' %>

app/views/teachers/new.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1>Nuevo Profesor</h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/show.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @teacher.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @teacher.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @teacher.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @teacher.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:about) %>:</strong></dt>
  <dd><%= @teacher.about %></dd>
</dl>

<%= link_to t('.back', :default => t("Regresar")),
              teachers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("Editar")),
              edit_teacher_path(@teacher), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("Eliminar")),
              teacher_path(@teacher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas Seguro?')) },
              :class => 'btn btn-danger' %>