config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :teachers, path_prefix: 'my'
  resources :teachers
  get 'teacher/course/:id' => 'teachers#course', as: 'teacher_course'
  get 'teacher/dashboard' => 'teachers#dashboard', as: 'teacher_dashboard'

  devise_for :students, path_prefix: 'my'
  resources :students
  get 'student/dashboard' => 'students#dashboard', as: 'student_dashboard'
  get 'student/course/:id' => 'students#course', as: 'student_course'
  get 'student/grade/:id' => 'students#grade', as: 'student_grade'
  get 'student/profile' => 'students#profile', as: 'student_profile'

  get 'student/change_grade/:id' => 'students#change_grade_student', as: 'change_grade_student'

  post 'student/enroll_student' => 'students#enroll_student', as: 'enroll_student'

  devise_for :users, path_prefix: 'my'
  resources :users

  resources :scores
  get 'score/edit_for_teacher/:id' => 'scores#edit_for_teacher', as: 'edit_score_for_teacher'

  resources :courses

  resources :grades

  resources :periods

  root 'welcome#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Rails College" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body class="admin">


<div class="navbar navbar-default navbar-static-top bar-top">
  <div class="container-fluid">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Rails College</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><a>Usuario: <strong><%= current_user.email %></strong></a></li>
        <% end %>
        <% if student_signed_in? %>
            <li><a>Estudiante: <strong><%= current_student.email %></strong></a></li>
        <% end %>
        <% if teacher_signed_in? %>
            <li><a>Maestro: <strong><%= current_teacher.email %></strong></a></li>
        <% end %>
        <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</div>

<div id="content" class="container-fluid">
  <div class="row">
    <div class="col-xs-2 col-md-2 col-lg-2 sidebar">
      <div class="sidebar-nav">

        <ul class="nav nav-pills nav-stacked">
          <% if user_signed_in? %>
              <li>
                <%= link_to grades_path do %>
                    <span class="fa fa-graduation-cap"></span>
                    <span class="hidden-xs">Grados</span>
                <% end %>
              </li>
              <li>
                <%= link_to courses_path do %>
                    <span class="fa fa-book"></span>
                    <span class="hidden-xs">Materias</span>
                <% end %>
              </li>
              <li>
                <%= link_to scores_path do %>
                    <span class="fa fa-check-circle"></span>
                    <span class="hidden-xs">Calificaciones</span>
                <% end %>
              </li>
              <li>
                <%= link_to students_path do %>
                    <span class="fa fa-users"></span>
                    <span class="hidden-xs">Estudiantes</span>
                <% end %>
              </li>
              <li>
                <%= link_to teachers_path do %>
                    <span class="fa fa-university"></span>
                    <span class="hidden-xs">Maestros</span>
                <% end %>
              </li>
              <%= drop_down '<span class="fa fa-cog fa-spin"></span> <span class="hidden-xs">Configuracion</span>' do %>
                  <%= menu_item "Períodos", periods_path %>
                  <%= menu_item "Usuarios", users_path %>
              <% end %>
              <hr/>
          <% end %>

          <% if student_signed_in? %>

              <h4><strong>Estudiante</strong></h4>
              <li>
                <%= link_to student_dashboard_path do %>
                    <span class="fa fa-home"></span>
                    <span class="hidden-xs">Inicio</span>
                <% end %>
              </li>

              <hr/>
          <% end %>
          <% if teacher_signed_in? %>

              <h4><strong>Maestro</strong></h4>
              <li>
                <%= link_to teacher_dashboard_path do %>
                    <span class="fa fa-home"></span>
                    <span class="hidden-xs">Inicio</span>
                <% end %>
              </li>

          <% end %>
        </ul>
      </div><!--/.well -->

    </div><!--/sidebar-->

    <div class="col-xs-10 col-md-10 col-lg-10 main">
      <%= bootstrap_flash %>
      <%= yield %>

      <footer>
        <hr/>
        <p>&copy; Company 2015</p>
      </footer>
    </div>

  </div><!--/row-->



</div> <!-- /container -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>COLEGIO12</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "TestAka" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body class="login">
<div class="container">
  <div class="row">
    <h1>Rails College 1.2</h1>
    <div class="login-container center-block">

      <%= bootstrap_flash %>
      <%= yield %>
    </div>

  </div><!--/row-->

  <footer>
    <p>&copy; Company 2015</p>
  </footer>

</div> <!-- /container -->

</body>
</html>